kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: compass-poc
nodes:
  # Control plane node
  - role: control-plane
    kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
    extraPortMappings:
    # Allow access to services via localhost
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP

  # Worker node 1 - simulated A100-80GB GPU
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "gpu-type=NVIDIA-A100-80GB,nvidia.com/gpu=true,gpu-count=2"

  # Worker node 2 - simulated L4 GPU
  - role: worker
    kubeadmConfigPatches:
    - |
      kind: JoinConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "gpu-type=NVIDIA-L4,nvidia.com/gpu=true,gpu-count=1"
